// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for suggesting relevant todos for a given activity title.
 *
 * The flow uses a language model to generate todo suggestions based on the provided activity title.
 * It exports:
 * - `suggestTodos`: The main function to trigger the todo suggestion flow.
 * - `SuggestTodosInput`: The input type for the suggestTodos function.
 * - `SuggestTodosOutput`: The output type for the suggestTodos function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Input schema for the suggestTodos function.
const SuggestTodosInputSchema = z.object({
  activityTitle: z.string().describe('The title of the activity for which to suggest todos.'),
});
export type SuggestTodosInput = z.infer<typeof SuggestTodosInputSchema>;

// Output schema for the suggestTodos function.
const SuggestTodosOutputSchema = z.object({
  todos: z.array(z.string()).describe('An array of suggested todos for the activity.'),
});
export type SuggestTodosOutput = z.infer<typeof SuggestTodosOutputSchema>;

/**
 * Suggests relevant todos for a given activity title.
 *
 * @param input - The input object containing the activity title.
 * @returns A promise that resolves to an object containing an array of suggested todos.
 */
export async function suggestTodos(input: SuggestTodosInput): Promise<SuggestTodosOutput> {
  return suggestTodosFlow(input);
}

// Define the prompt for suggesting todos.
const suggestTodosPrompt = ai.definePrompt({
  name: 'suggestTodosPrompt',
  input: {schema: SuggestTodosInputSchema},
  output: {schema: SuggestTodosOutputSchema},
  prompt: `Suggest 5 todos for the following activity: {{{activityTitle}}}. Return only the todos in a JSON array of strings.
`,
});

// Define the Genkit flow for suggesting todos.
const suggestTodosFlow = ai.defineFlow(
  {
    name: 'suggestTodosFlow',
    inputSchema: SuggestTodosInputSchema,
    outputSchema: SuggestTodosOutputSchema,
  },
  async input => {
    const {output} = await suggestTodosPrompt(input);
    return output!;
  }
);
